import { Footer } from '@/sections'
import '@/styles/globals.scss'


export const metadata = {
  title: 'My Order',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  )
}
