import {OrderProvider, SearchProvider, TableProvider } from '@/context'
import '@/styles/globals.scss'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <TableProvider>
          <OrderProvider>
            <SearchProvider>
              <body>
                {children}
              </body>
            </SearchProvider>
          </OrderProvider>
        </TableProvider>
    </html>
  )
}
