import { /* AdminProvider,*/ OrderProvider, SearchProvider, TableProvider } from '@/context'
/* import { FooterView as Footer, MainHome, Navbar } from '@/sections' */
import '@/styles/globals.scss'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
{/*       <AdminProvider> */}
        <TableProvider>
          <OrderProvider>
            <SearchProvider>
              <body>
                {children}
              </body>
            </SearchProvider>
          </OrderProvider>
        </TableProvider>
    {/*   </AdminProvider> */}
    </html>
  )
}
