export * from './icons/Requireds'
export * from './cards/CallWaiter'
export * from './inputs/InputSearch'
export * from './cards/Categories'
export * from './forms/FormSearch/FormSearchView'
export * from './cards/Plates'
export * from './cards/MainPlates'
export * from './cards/MainPlate'
export * from './cards/MenuPlates'
export * from './cards/ModalPlate'
export * from './loading/MainLoading'
export * from './cards/ModalInfo'
export * from './cards/ModalPlateRequired'
export * from './inputs/Quantity'
/* export * from './cards/OrderPlateUnConfirmed'
export * from './cards/OrdersPlatesUnconfirmed'
export * from './cards/OrderPlateConfirmed'
export * from './cards/OrdersPlatesConfirmed'  */
