export * from './cards/CallWaiter'
export * from './inputs/InputSearch'
export * from './cards/Categories'
export * from './forms/FormSearch/FormSearch'
export * from './cards/Plates'
export * from './cards/MainPlates'
export * from './cards/MainPlate'
export * from './cards/MenuPlates'
export * from './cards/MenuPlate'
export * from './cards/ModalInfo'
export * from './cards/OrderPlate'
export * from './cards/OrdersPlates'
export * from './cards/ModalPlateRequired'
export * from './cards/Modals'
export * from './cards/Swiper'
export * from './inputs/Quantity'


